# 赞助配置
# 文档：https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
github: baosfeng

# Patreon
# patreon: # Replace with a single Patreon username

# Open Collective
# open_collective: # Replace with a single Open Collective username

# Ko-fi
# ko_fi: # Replace with a single Ko-fi username

# Tidelift
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel

# Community Bridge
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry

# Liberapay
# liberapay: # Replace with a single Liberapay username

# IssueHunt
# issuehunt: # Replace with a single IssueHunt username

# LFX Crowdfunding
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry

# Polar
# polar: # Replace with a single Polar username

# Buy Me a Coffee
# buy_me_a_coffee: # Replace with a single Buy Me a Coffee username

# Thanks.dev
# thanks_dev: # Replace with a single Thanks.dev username

# Custom
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
