// ── 公式命令 → Unicode 映射表（issue #82）：希腊字母 / 求和积分 /
//    常见符号 / 函数名文本 / \text 类文本命令。由 math.ts 的
//    parseCommand / parseDelim 查表；零运行时依赖（R10）。
const GREEK_COMMANDS: Record<string, string> = {
  alpha: 'α',
  beta: 'β',
  gamma: 'γ',
  delta: 'δ',
  epsilon: 'ε',
  varepsilon: 'ϵ',
  zeta: 'ζ',
  eta: 'η',
  theta: 'θ',
  vartheta: 'ϑ',
  iota: 'ι',
  kappa: 'κ',
  lambda: 'λ',
  mu: 'μ',
  nu: 'ν',
  xi: 'ξ',
  omicron: 'ο',
  pi: 'π',
  varpi: 'ϖ',
  rho: 'ρ',
  varrho: 'ϱ',
  sigma: 'σ',
  varsigma: 'ς',
  tau: 'τ',
  upsilon: 'υ',
  phi: 'φ',
  varphi: 'ϕ',
  chi: 'χ',
  psi: 'ψ',
  omega: 'ω',
  Gamma: 'Γ',
  Delta: 'Δ',
  Theta: 'Θ',
  Lambda: 'Λ',
  Xi: 'Ξ',
  Pi: 'Π',
  Sigma: 'Σ',
  Upsilon: 'Υ',
  Phi: 'Φ',
  Psi: 'Ψ',
  Omega: 'Ω',
}

const MATH_BIG_SYMS: Record<string, string> = {
  sum: '∑',
  int: '∫',
  prod: '∏',
  coprod: '∐',
  bigcup: '⋃',
  bigcap: '⋂',
  bigoplus: '⨁',
  bigotimes: '⨂',
  oint: '∮',
  iint: '∬',
  iiint: '∭',
}

const MATH_SYMBOLS: Record<string, string> = {
  times: '×',
  cdot: '⋅',
  pm: '±',
  mp: '∓',
  div: '÷',
  leq: '≤',
  geq: '≥',
  neq: '≠',
  approx: '≈',
  equiv: '≡',
  sim: '∼',
  simeq: '≃',
  propto: '∝',
  in: '∈',
  notin: '∉',
  subset: '⊂',
  supset: '⊃',
  subseteq: '⊆',
  supseteq: '⊇',
  cup: '∪',
  cap: '∩',
  setminus: '∖',
  emptyset: '∅',
  varnothing: '∅',
  forall: '∀',
  exists: '∃',
  nexists: '∄',
  neg: '¬',
  land: '∧',
  lor: '∨',
  to: '→',
  rightarrow: '→',
  leftarrow: '←',
  leftrightarrow: '↔',
  Rightarrow: '⇒',
  Leftarrow: '⇐',
  Leftrightarrow: '⇔',
  mapsto: '↦',
  ldots: '…',
  cdots: '⋯',
  vdots: '⋮',
  ddots: '⋱',
  infty: '∞',
  nabla: '∇',
  partial: '∂',
  hbar: 'ℏ',
  ell: 'ℓ',
  prime: '′',
  deg: '°',
  circ: '∘',
  bullet: '∙',
  dagger: '†',
  ddagger: '‡',
  parallel: '∥',
  perp: '⊥',
  angle: '∠',
  triangle: '△',
  square: '□',
  aleph: 'ℵ',
  Re: 'ℜ',
  Im: 'ℑ',
  oplus: '⊕',
  ominus: '⊖',
  otimes: '⊗',
  oslash: '⊘',
  odot: '⊙',
  ast: '∗',
  star: '⋆',
}

/** 函数名命令 → 罗马文本（\sin → sin）。 */
const MATH_FUNC_TEXT: Record<string, string> = {
  sin: 'sin',
  cos: 'cos',
  tan: 'tan',
  cot: 'cot',
  sec: 'sec',
  csc: 'csc',
  arcsin: 'arcsin',
  arccos: 'arccos',
  arctan: 'arctan',
  sinh: 'sinh',
  cosh: 'cosh',
  tanh: 'tanh',
  log: 'log',
  ln: 'ln',
  exp: 'exp',
  lim: 'lim',
  max: 'max',
  min: 'min',
  det: 'det',
  gcd: 'gcd',
  inf: 'inf',
  sup: 'sup',
}

/** 文本命令：参数组内容按普通文本内联（\text{if} → if）。 */
const MATH_TEXT_CMDS: readonly string[] = [
  'text',
  'textrm',
  'mathrm',
  'mathbf',
  'mathit',
  'mathsf',
  'mathtt',
  'operatorname',
]
